// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vodexhppkasbulogmcqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZGV4aHBwa2FzYnVsb2dtY3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMTE3MzksImV4cCI6MjA1MTc4NzczOX0.c98G9mQd4r40IjPQc0lprI0UMOIv8mq4FjC6welXkeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);