name: Scheduled Follow-up Processing

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  process-follow-ups:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Follow-ups
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "Starting follow-up processing at $(date)"
          curl -X POST 'https://vodexhppkasbulogmcqb.supabase.co/functions/v1/get-follow-up-contacts' \
          -H "Authorization: Bearer ${SUPABASE_KEY}" \
          -H "Content-Type: application/json" \
          -H "apikey: ${SUPABASE_KEY}" \
          --data-raw '{"scheduled":true, "source": "github-action"}' \
          --fail \
          --show-error \
          --silent \
          || echo "Error: Failed to process follow-ups"
          echo "Completed follow-up processing at $(date)"