name: Scheduled Follow-up Processing

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:      # Allows manual triggering

jobs:
  process-follow-ups:
    name: Process Follow-ups
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Process Follow-ups
        id: process
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Starting follow-up processing at ${timestamp}"
          
          if [ -z "$SUPABASE_KEY" ]; then
            echo "::error::SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi
          
          response=$(curl -X POST \
            'https://vodexhppkasbulogmcqb.supabase.co/functions/v1/get-follow-up-contacts' \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "apikey: ${SUPABASE_KEY}" \
            --data-raw "{\"scheduled\":true, \"source\":\"github-action\", \"timestamp\":\"${timestamp}\"}" \
            --fail \
            --show-error \
            --silent)
          
          status=$?
          
          if [ $status -eq 0 ]; then
            echo "✅ Follow-up processing completed successfully"
            echo "Response: ${response}"
          else
            echo "❌ Error processing follow-ups (Status: ${status})"
            echo "Error response: ${response}"
            exit 1
          fi
          
          echo "Completed follow-up processing at $(date '+%Y-%m-%d %H:%M:%S')"
      
      - name: Handle Failure
        if: failure()
        run: |
          echo "❌ Follow-up processing job failed at $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Please check the logs above for more details"