name: Follow-up Processing

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:        # Allows manual triggering

concurrency:
  group: follow-up-processing
  cancel-in-progress: true

jobs:
  process-follow-ups:
    name: Process Follow-ups
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Process Follow-ups
        id: process
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Starting follow-up processing at ${timestamp}"
          
          if [ -z "$SUPABASE_KEY" ]; then
            echo "::error::SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi
          
          curl -X POST \
            'https://vodexhppkasbulogmcqb.supabase.co/functions/v1/get-follow-up-contacts' \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "apikey: ${SUPABASE_KEY}" \
            --data-raw "{\"scheduled\":true, \"source\":\"github-action\", \"timestamp\":\"${timestamp}\"}" \
            --fail \
            --show-error \
            || {
              echo "❌ Error processing follow-ups"
              exit 1
            }
          
          echo "✅ Follow-up processing completed at $(date '+%Y-%m-%d %H:%M:%S')"